---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearmor-1.3.2-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    autoDeploy: true
    
    kubearmorOperator:
      name: kubearmor-operator
      image:
        repository: kubearmor/kubearmor-operator
        tag: v1.3.2
      imagePullPolicy: Always
      
    kubearmorConfig:
      defaultCapabilitiesPosture: audit
      defaultFilePosture: audit
      defaultNetworkPosture: audit
      defaultVisibility: process,network
