---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubearmor-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubearmor-operator
      sourceRef:
        kind: HelmRepository
        name: kubearmor/kubearmor-operator
        namespace: ${releaseNamespace}
      version: v1.3.2
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: 
  valuesFrom:
    - kind: ConfigMap
      name: kubearmor-1.3.2-defaults
  targetNamespace: ${releaseNamespace}
